persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

listener 1883
allow_anonymous true

# 在生产环境中，建议将 allow_anonymous 设置为 false 并配置密码文件
# password_file /mosquitto/config/password_file
